export const SANDWICHES = {
    breakfast: {
      label: "🍳 Breakfast",
      items: {
        bs_0: "Ham, Egg, and Cheese",
        bs_1: "Sausage, Egg, and Cheese",
        bs_2: "Double Egg and Cheese",
        bs_3: "Eggs on the Beach",
        bs_4: "Chicken, Sausage, Egg and Cheese",
        bs_5: "Bacon, Egg and Cheese",
        bs_6: "Vegan Breakfast Sandwich",
      },
    },
    subs: {
      label: "🥖 Subs & Sandwiches",
      items: {
        s_0: "The Hemenway",
        s_1: "The Fenway",
        s_2: "The Northeastern",
        s_3: "The Huntington",
        s_4: "The Huskie",
        s_5: "Marino Fitness",
        s_6: "The Boston Connection",
        s_7: "Chicken Salad",
        s_8: "Game of Thrones",
        s_9: "George Likes his Chicken Spicy",
        s_10: "Phi Gamma Melta",
        s_11: "Steak and Cheese",
        s_12: "The Symphony",
        s_13: "Tuna Salad",
        s_14: "Buffalo Chicken Tender Sub",
        s_15: "Gobbler",
        s_16: "Lighten Up Francis",
        s_17: "Meatball Sub",
        s_18: "Notorious DTD",
        s_19: "The Pike",
        s_20: "Healthy Choice",
      },
    },
  };