export const SANDWICHES = {
    breakfast: {
      label: "🍳 Breakfast",
      items: {
        bs_0: "Ham, Egg, and Cheese",
        bs_1: "Sausage, Egg, and Cheese",
        bs_2: "Double Egg and Cheese",
        bs_3: "Eggs on the Beach",
        bs_4: "Chicken, Sausage, Egg and Cheese",
        bs_5: "Bacon, Egg and Cheese",
        bs_6: "Vegan Breakfast Sandwich",
      },
    },
    subs: {
      label: "🥖 Subs & Sandwiches",
      items: {
        s_0:  "The Hemenway",
        s_1:  "The Fenway",
        s_2:  "The Northeastern",
        s_3:  "The Huntington",
        s_4:  "The Huskie",
        s_5:  "Marino Fitness",
        s_6:  "The Boston Connection",
        s_7:  "Chicken Salad",
        s_8:  "Game of Thrones",
        s_9:  "George Likes his Chicken Spicy",
        s_10: "Phi Gamma Melta",
        s_11: "Steak and Cheese",
        s_12: "The Symphony",
        s_13: "Tuna Salad",
        s_14: "Buffalo Chicken Tender Sub",
        s_15: "Gobbler",
        s_16: "Lighten Up Francis",
        s_17: "Meatball Sub",
        s_18: "Notorious DTD",
        s_19: "The Pike",
        s_20: "Healthy Choice",
        s_21: "Heena's Black Bean Burger",
        s_22: "Pulled Pork Sandwich",
        s_23: "The Big Apple",
        s_24: "Uncle Leo",
        s_25: "Green Monster",
        s_26: "Mookie B.A.T.S",
        s_27: "Tuscano",
        s_28: "Ninja",
        s_29: "Champion",
        s_30: "Veggie Delight",
        s_31: "Roast Beef Deluxe",
        s_32: "Turkey Reuben",
        s_33: "No Name",
        s_34: "A.E. Pi Special",
        s_35: "Cubano",
        s_36: "Kappa Sig",
        s_37: "Sigma Kappanini",
        s_38: "Wentworth",
        s_39: "Chicken and Prosciutto",
        s_40: "Et Tu Brute",
        s_41: "Kappa Wrap",
        s_42: "Paisano",
        s_43: "Youssef's Halal Sandwich",
        s_44: "Alpha Delt Melt",
        s_45: "Hot Pastrami",
        s_46: "Sig. Ep",
        s_47: "Southern Smokehouse",
        s_48: "Wild One",
      },
    },
  };
  
  // Flat list of all sandwich IDs across all categories, used for batch queries
  export const ALL_SANDWICH_IDS = Object.values(SANDWICHES)
    .flatMap(cat => Object.keys(cat.items));